// 本文件提供默认减伤清单（参考 JobBars 的常用减伤配置），用于首次启动初始化。
using System.Collections.Generic;
using MitigationPolice.Models;

namespace MitigationPolice.Mitigations;

public static class DefaultMitigationLibrary {
    public static List<MitigationDefinition> Build() {
        var tanks = new List<JobIds> { JobIds.PLD, JobIds.WAR, JobIds.DRK, JobIds.GNB };
        var melee = new List<JobIds> { JobIds.MNK, JobIds.DRG, JobIds.NIN, JobIds.SAM, JobIds.RPR, JobIds.VPR };
        var casters = new List<JobIds> { JobIds.BLM, JobIds.SMN, JobIds.RDM, JobIds.PCT, JobIds.BLU };

        return new List<MitigationDefinition> {
            new() {
                Id = "rampart",
                Name = "铁壁",
                IconActionId = 7531,
                TriggerActionIds = new List<uint> { 7531 },
                DurationSeconds = 20,
                CooldownSeconds = 90,
                Category = MitigationCategory.Personal,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = tanks,
                Enabled = true,
            },
            new() {
                Id = "reprisal",
                Name = "雪仇",
                IconActionId = 7535,
                TriggerActionIds = new List<uint> { 7535 },
                DurationSeconds = 15,
                CooldownSeconds = 60,
                Category = MitigationCategory.EnemyDebuff,
                ApplyTo = MitigationApplyTo.Source,
                Jobs = tanks,
                Enabled = true,
            },

            new() {
                Id = "addle",
                Name = "昏乱",
                IconActionId = 7560,
                TriggerActionIds = new List<uint> { 7560 },
                DurationSeconds = 15,
                CooldownSeconds = 90,
                Category = MitigationCategory.EnemyDebuff,
                ApplyTo = MitigationApplyTo.Source,
                Jobs = casters,
                Enabled = true,
            },
            new() {
                Id = "feint",
                Name = "牵制",
                IconActionId = 7549,
                TriggerActionIds = new List<uint> { 7549 },
                DurationSeconds = 15,
                CooldownSeconds = 90,
                Category = MitigationCategory.EnemyDebuff,
                ApplyTo = MitigationApplyTo.Source,
                Jobs = melee,
                Enabled = true,
            },
            new() {
                Id = "dismantle",
                Name = "武装解除",
                IconActionId = 2887,
                TriggerActionIds = new List<uint> { 2887 },
                DurationSeconds = 10,
                CooldownSeconds = 120,
                Category = MitigationCategory.EnemyDebuff,
                ApplyTo = MitigationApplyTo.Source,
                Jobs = new List<JobIds> { JobIds.MCH },
                Enabled = true,
            },

            new() {
                Id = "troubadour",
                Name = "行吟",
                IconActionId = 7405,
                TriggerActionIds = new List<uint> { 7405 },
                DurationSeconds = 15,
                CooldownSeconds = 90,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.BRD },
                Enabled = true,
            },
            new() {
                Id = "tactician",
                Name = "策动",
                IconActionId = 16889,
                TriggerActionIds = new List<uint> { 16889 },
                DurationSeconds = 15,
                CooldownSeconds = 90,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.MCH },
                Enabled = true,
            },
            new() {
                Id = "shield_samba",
                Name = "防守之桑巴",
                IconActionId = 16012,
                TriggerActionIds = new List<uint> { 16012 },
                DurationSeconds = 15,
                CooldownSeconds = 90,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.DNC },
                Enabled = true,
            },

            new() {
                Id = "temperance",
                Name = "节制",
                IconActionId = 16536,
                TriggerActionIds = new List<uint> { 16536 },
                DurationSeconds = 20,
                CooldownSeconds = 120,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.WHM },
                Enabled = true,
            },
            new() {
                Id = "aquaveil",
                Name = "水流幕",
                IconActionId = 25861,
                TriggerActionIds = new List<uint> { 25861 },
                DurationSeconds = 8,
                CooldownSeconds = 60,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.WHM },
                Enabled = true,
            },

            new() {
                Id = "sacred_soil",
                Name = "野战治疗阵",
                IconActionId = 188,
                TriggerActionIds = new List<uint> { 188 },
                DurationSeconds = 15,
                CooldownSeconds = 30,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.SCH },
                Enabled = true,
            },
            new() {
                Id = "fey_illumination",
                Name = "异想的幻光",
                IconActionId = 805,
                TriggerActionIds = new List<uint> { 805 },
                DurationSeconds = 20,
                CooldownSeconds = 120,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.SCH },
                Enabled = true,
            },
            new() {
                Id = "expedient",
                Name = "疾风怒涛之计",
                IconActionId = 25868,
                TriggerActionIds = new List<uint> { 25868 },
                DurationSeconds = 20,
                CooldownSeconds = 120,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.SCH },
                Enabled = true,
            },

            new() {
                Id = "collective_unconscious",
                Name = "命运之轮",
                IconActionId = 3613,
                TriggerActionIds = new List<uint> { 3613 },
                DurationSeconds = 10,
                CooldownSeconds = 60,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.AST },
                Enabled = true,
            },
            new() {
                Id = "exaltation",
                Name = "擢升",
                IconActionId = 25873,
                TriggerActionIds = new List<uint> { 25873 },
                DurationSeconds = 8,
                CooldownSeconds = 60,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.AST },
                Enabled = true,
            },

            new() {
                Id = "kerachole",
                Name = "坚角清汁",
                IconActionId = 24298,
                TriggerActionIds = new List<uint> { 24298 },
                DurationSeconds = 15,
                CooldownSeconds = 30,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.SGE },
                Enabled = true,
            },
            new() {
                Id = "taurochole",
                Name = "白牛清汁",
                IconActionId = 24303,
                TriggerActionIds = new List<uint> { 24303 },
                DurationSeconds = 15,
                CooldownSeconds = 45,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.SGE },
                Enabled = true,
            },
            new() {
                Id = "holos",
                Name = "整体论",
                IconActionId = 24310,
                TriggerActionIds = new List<uint> { 24310 },
                DurationSeconds = 20,
                CooldownSeconds = 120,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.SGE },
                Enabled = true,
            },

            new() {
                Id = "hallowed_ground",
                Name = "神圣领域",
                IconActionId = 30,
                TriggerActionIds = new List<uint> { 30 },
                DurationSeconds = 10,
                CooldownSeconds = 420,
                Category = MitigationCategory.Personal,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.PLD },
                Enabled = true,
            },
            new() {
                Id = "divine_veil",
                Name = "圣光幕帘",
                IconActionId = 3540,
                TriggerActionIds = new List<uint> { 3540 },
                DurationSeconds = 30,
                CooldownSeconds = 90,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.PLD },
                Enabled = true,
            },
            new() {
                Id = "passage_of_arms",
                Name = "武装戍卫",
                IconActionId = 7385,
                TriggerActionIds = new List<uint> { 7385 },
                DurationSeconds = 18,
                CooldownSeconds = 120,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.PLD },
                Enabled = true,
            },

            new() {
                Id = "holmgang",
                Name = "死斗",
                IconActionId = 43,
                TriggerActionIds = new List<uint> { 43 },
                DurationSeconds = 10,
                CooldownSeconds = 240,
                Category = MitigationCategory.Personal,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.WAR },
                Enabled = true,
            },
            new() {
                Id = "shake_it_off",
                Name = "摆脱",
                IconActionId = 7388,
                TriggerActionIds = new List<uint> { 7388 },
                DurationSeconds = 30,
                CooldownSeconds = 90,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.WAR },
                Enabled = true,
            },
            new() {
                Id = "bloodwhetting",
                Name = "原初的血气/原初的直觉/原初的勇猛",
                IconActionId = 25751,
                TriggerActionIds = new List<uint> { 16464, 3551, 25751 },
                DurationSeconds = 8,
                DurationSecondsByActionId = new Dictionary<uint, float> {
                    [3551] = 6,
                    [16464] = 8,
                    [25751] = 8,
                },
                CooldownSeconds = 25,
                Category = MitigationCategory.Personal,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.WAR },
                Enabled = true,
            },

            new() {
                Id = "living_dead",
                Name = "行尸走肉",
                IconActionId = 3638,
                TriggerActionIds = new List<uint> { 3638 },
                DurationSeconds = 10,
                CooldownSeconds = 300,
                Category = MitigationCategory.Personal,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.DRK },
                Enabled = true,
            },
            new() {
                Id = "dark_missionary",
                Name = "暗黑布道",
                IconActionId = 16471,
                TriggerActionIds = new List<uint> { 16471 },
                DurationSeconds = 15,
                CooldownSeconds = 90,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.DRK },
                Enabled = true,
            },
            new() {
                Id = "the_blackest_night",
                Name = "至黑之夜",
                IconActionId = 7393,
                TriggerActionIds = new List<uint> { 7393 },
                DurationSeconds = 7,
                CooldownSeconds = 15,
                Category = MitigationCategory.Personal,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.DRK },
                Enabled = true,
            },

            new() {
                Id = "superbolide",
                Name = "超火流星",
                IconActionId = 16152,
                TriggerActionIds = new List<uint> { 16152 },
                DurationSeconds = 10,
                CooldownSeconds = 360,
                Category = MitigationCategory.Personal,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.GNB },
                Enabled = true,
            },
            new() {
                Id = "heart_of_light",
                Name = "光之心",
                IconActionId = 16160,
                TriggerActionIds = new List<uint> { 16160 },
                DurationSeconds = 15,
                CooldownSeconds = 90,
                Category = MitigationCategory.Party,
                ApplyTo = MitigationApplyTo.Target,
                Jobs = new List<JobIds> { JobIds.GNB },
                Enabled = true,
            },
        };
    }
}
